#!/bin/bash
# /etc/init.d/brewninja

### BEGIN INIT INFO
# Provides:          brewninja
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       https://github.com/jcreason/brewninja
### END INIT INFO

## Fill in name of program here.
PROG="brewninja"
PID_PATH="/var/run/"

export JAVA_HOME=/usr/local/jdk
export PATH=$PATH:$JAVA_HOME/bin
export M2_HOME=/usr/local/apache-maven
export M2=$M2_HOME/bin
export PATH=$PATH:$M2


start() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        ## Program is running, exit with error.
        echo "Error! $PROG is currently running!" 1>&2
        exit 1
    else
        # fire up the temp sensors
        modprobe w1-gpio
        modprobe w1-therm

        ## Change from /dev/null to something like /var/log/$PROG if you want to save output.
        /usr/local/apache-maven/bin/mvn -f /home/pi/brewninja/pom.xml exec:java -Dproperties=brewninja 2>&1 >/dev/null &
        echo "$PROG started"
        sleep 1
        ps -aef | grep java | grep brewninja | grep -v grep | awk '{print $2}' > "$PID_PATH/$PROG.pid"
    fi
}

stop() {
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        ## Program is running, so stop it
        kill `cat "$PID_PATH/$PROG.pid"`

        rm "$PID_PATH/$PROG.pid"

        echo "$PROG stopped"
    else
        ## Program is not running, exit with error.
        echo "Error! $PROG not started!" 1>&2
        exit 1
    fi
}

## Check to see if we are running as root first.
## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|restart}" 1>&2
        exit 1
    ;;
esac

exit 0
